x=("AKSHAT","20MIS0183","BIHAR","COMPUTER")
print("THE ORIGINAL TUPLE")
print(x)
print("\n")
y=list(x)
print("LIST AS TUPLE")
print(y)
print("\n")
y.append("VIT")
x=tuple(y)
print("TUPLE AFTER ADDING ELEMENTS")
print(x)