x=("MY SUBJECTS","ENGLISH","COMPUTER","EVS","CHEMISTRY","PHYSICS")
print("THE ORIGINAL TUPLE")
print(x)
print("\n")
y=list(x)
print("THE TUPLE AS A LIST")
print(y)
print("\n")
y.remove("EVS")
x=tuple(y)
print("TUPLE AFTER REMOVING A SUBJECT")
print(x)